[env:esp32s3]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; 8MB Flash
board_build.partitions = default_8MB.csv

; N8R2 uses 8MB Flash + 2MB PSRAM (QSPI)
board_build.arduino.memory_type = qio_qspi
build_flags = -DBOARD_HAS_PSRAM

; the size of the flash memory that can be used for programming.
board_upload.flash_size = 8MB

; Libraries used by src/main.cpp
lib_deps =
    chrisjoyce911/esp32FOTA
    tzapu/WiFiManager
    bblanchon/ArduinoJson
    256dpi/MQTT
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit NeoPixel@^1.12.3
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0